config/routes.rb
Rails.application.routes.draw do
  get 'admin/index'
  namespace :admin do
    resources :contacts
    resources :members
  end
  devise_for :users
  root to: "main#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
has_and_belongs_to_many :users, :join_table => :users_admins


belongs_to :resource,
           :polymorphic => true,
           :optional => true


validates :resource_type,
          :inclusion => { :in => Rolify.resource_types },
          :allow_nil => true

scopify
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  def full_address
    "#{self.city}, #{self.uf} #{self.neighborhood} #{self.number} - #{self.cep}"
  end
end

app/models/member.rb
class Member < ApplicationRecord
  has_one_attached :photo

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :ocupation, presence: true

  def name
    "#{self.first_name} #{self.last_name}"
  end
end

app/models/user.rb
class User < ApplicationRecord
  rolify :role_cname => 'Admin'
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/contacts_controller.rb
class Admin::ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]
  layout 'admin'
  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to admin_contact_path(@contact), notice: 'Seção de Contato foi criada com sucesso.' }
        format.json { render :show, status: :created, location: admin_contact_path(@contact) }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to admin_contact_path(@contact), notice: 'Seção de Contato foi atualizada com sucesso.' }
        format.json { render :show, status: :ok, location: admin_contact_path(@contact) }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to admin_contacts_url, notice: 'Seção de Contato foi deletada com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:body, :city, :uf, :number, :neighborhood, :cep, :phone, :email)
    end
end

app/controllers/admin/members_controller.rb
class Admin::MembersController < ApplicationController
  before_action :set_member, only: [:show, :edit, :update, :destroy]
  layout 'admin'
  # GET /members
  # GET /members.json
  def index
    @members = Member.all
  end

  # GET /members/1
  # GET /members/1.json
  def show
  end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(member_params)
    @member.photo.attach(params[:photo])

    respond_to do |format|
      if @member.save
        format.html { redirect_to admin_member_path(@member), notice: 'Member was successfully created.' }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1
  # PATCH/PUT /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to admin_member_path(@member), notice: 'Member was successfully updated.' }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member.destroy
    respond_to do |format|
      format.html { redirect_to admin_members_url, notice: 'Member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def member_params
      params.require(:member).permit(:first_name, :last_name, :ocupation, :twitter_url, :facebook_url, :instagram_url, :photo)
    end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :require_admin

  def index
    @contact = Contact.last
  end

  protected

  def require_admin
    if user_signed_in?
      unless current_user.has_role? :admin
        flash[:danger] = "Restrito a administradores"
        redirect_to root_path
      end
    else
      flash[:danger] = "Restrito a administradores"
      redirect_to root_path
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    @contact = Contact.last
    @members = Member.all
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/admin/contacts/_form.html.erb
<%= form_with(model: contact,url: admin_contact_path(contact),method: :patch, local: true,html: {class: "forms-sample"}) do |form| %>
  <% if contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :texto %>
    <%= form.text_area :body,class: "form-control p-input", placeholder: "Coloque o texto que irá aparecer no início na seção 'Contato' ", style: "min-height: 80px;" %>
  </div>

  <div class="form-group">
    <%= form.label :cep %>
    <%= form.text_field :cep, onkeypress: "mascara(this, '##.###-###')", maxlength:"10", class: "form-control p-input", placeholder: "CEP" %>
  </div>

  <div class="form-group">
    <%= form.label :cidade %>
    <%= form.text_field :city,class: "form-control p-input", placeholder: "Cidade" %>
  </div>

  <div class="form-group">
    <%= form.label :uf %>
    <%= form.text_field :uf,class: "form-control p-input", placeholder: "UF" %>
  </div>

  <div class="form-group">
    <%= form.label :número %>
    <%= form.number_field :number,class: "form-control p-input", placeholder: "nº" %>
  </div>

  <div class="form-group">
    <%= form.label :bairro%>
    <%= form.text_field :neighborhood,class: "form-control p-input", placeholder: "Bairro" %>
  </div>


  <div class="form-group">
    <%= form.label :telefone %>
    <%= form.text_field :phone, onkeypress: "mascara(this, '## #####-####')", maxlength:"13", class: "form-control p-input", placeholder: "Telefone" %>
  </div>

  <div class="form-group">
    <%= form.label :email %>
    <%= form.text_field :email,class: "form-control p-input", placeholder: "Email" %>
  </div>

  <div class="actions">
    <%= form.submit "Enviar", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/admin/contacts/edit.html.erb
<h1>Editar seção 'Contato'</h1>

<%= render 'form', contact: @contact %>

<script language="JavaScript">
    /*
    A função Mascara tera como valores no argumento os dados inseridos no input (ou no evento onkeypress)
    onkeypress="mascara(this, '## ####-####')"
    onkeypress = chama uma função quando uma tecla é pressionada, no exemplo acima, chama a função mascara e define os valores do argumento na função
    O primeiro valor é o this, é o Apontador/Indicador da Mascara, o '## ####-####' é o modelo / formato da mascara
    no exemplo acima o # indica os números, e o - (hifen) o caracter que será inserido entre os números, ou seja, no exemplo acima o telefone ficara assim: 11-4000-3562
    para o celular de são paulo o modelo deverá ser assim: '## #####-####' [11 98563-1254]
    para o RG '##.###.###.# [40.123.456.7]
    para o CPF '###.###.###.##' [789.456.123.10]
    Ou seja esta mascara tem como objetivo inserir o hifen ou espaço automáticamente quando o usuário inserir o número do celular, cpf, rg, etc

    lembrando que o hifen ou qualquer outro caracter é contado tambem, como: 11-4561-6543 temos 10 números e 2 hifens, por isso o valor de maxlength será 12
    <input type="text" name="telefone" onkeypress="mascara(this, '## ####-####')" maxlength="12">
    neste código não é possivel inserir () ou [], apenas . (ponto), - (hifén) ou espaço
    */

    function mascara(t, mask){
        var i = t.value.length;
        var saida = mask.substring(1,0);
        var texto = mask.substring(i)
        if (texto.substring(0,1) != saida){
            t.value += texto.substring(0,1);
        }
    }
</script>

app/views/admin/contacts/index.html.erb
<h1>Contacts</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th>City</th>
      <th>Uf</th>
      <th>Number</th>
      <th>Neighborhood</th>
      <th>Cep</th>
      <th>Phone</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.body %></td>
        <td><%= contact.city %></td>
        <td><%= contact.uf %></td>
        <td><%= contact.number %></td>
        <td><%= contact.neighborhood %></td>
        <td><%= contact.cep %></td>
        <td><%= contact.phone %></td>
        <td><%= contact.email %></td>
        <td><%= link_to 'Show', admin_contact_path(contact) %></td>
        <td><%= link_to 'Edit', edit_admin_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', admin_contact_path(contact), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_admin_contact_path %>

app/views/admin/contacts/new.html.erb
<h1>New Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Back', contacts_path %>

app/views/admin/contacts/show.html.erb
<div class="card-deck">
  <div class="card col-xl-6 col-lg-6 col-md-12 col-sm-12 mb-4">
    <div class="card-body">
      <h5 class="card-title mb-4">Texto</h5>
      <div class="row d-flex align-items-center justify-items-center flex-column">
        <div class="text-center mt-3">
          <i class="fa fa-quote-right icon-grey-big"></i>
        </div>
        <p class="font-italic text-muted mt-3 mb-4 text-center">
          <%= @contact.body %>
        </p>
      </div>
    </div>
  </div>
  <div class="card col-xl-3 col-lg-3 col-md-6 col-sm-6 mb-4">
    <div class="card-body">
      <h5 class="card-title mb-4">Endereço</h5>
      <div class="row d-flex align-items-center justify-items-center flex-column">
        <div class="text-center mt-3">
          <i class="fa fa-address-book icon-grey-big"></i>
        </div>
        <p class="font-italic text-muted mt-3 mb-4 text-center">
          <%= @contact.full_address %>
        </p>
      </div>
    </div>
  </div>
  <div class="card col-xl-3 col-lg-3 col-md-6 col-sm-6 mb-4">
    <div class="card-body">
      <h5 class="card-title mb-4">Telefone</h5>
      <div class="row d-flex align-items-center justify-items-center flex-column">
        <div class="text-center mt-3">
          <i class="fa fa-phone icon-grey-big"></i>
        </div>
        <p class="font-italic text-muted mt-3 mb-4 text-center">
          <%= @contact.phone %>
        </p>
      </div>
    </div>
  </div>
</div>
<div class="card-deck">
  <div class="card col-xl-3 col-lg-3 col-md-6 col-sm-6 mb-4">
    <div class="card-body">
      <h5 class="card-title mb-4">Email</h5>
      <div class="row d-flex align-items-center justify-items-center flex-column">
        <div class="text-center mt-3">
          <i class="fa fa-envelope icon-grey-big"></i>
        </div>
        <p class="font-italic text-muted mt-3 mb-4 text-center">
          <%= @contact.email %>
        </p>
      </div>
    </div>
  </div>
</div>

<%= link_to "Editar", edit_admin_contact_path(@contact),class: "btn btn-primary" %>

app/views/admin/index.html.erb
<h3 class="page-heading mb-4">Seções</h3>
<div class="row">
  <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 mb-4">
    <div class="card card-statistics">
      <div class="card-body">
        <div class="clearfix">
          <div class="float-left">
            <h4 class="text-danger">
              <i class="fa fa-address-book-o highlight-icon" aria-hidden="true"></i>
            </h4>
          </div>
          <div class="float-right">
            <p class="card-text text-dark">Contato</p>
            <%= link_to "Editar", edit_admin_contact_path(@contact),class: "btn btn-primary" %>
          </div>
        </div>
        <p class="text-muted">
          <i class="fa fa-exclamation-circle mr-1" aria-hidden="true"></i> Contato
        </p>
      </div>
    </div>
  </div>
  <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 mb-4">
    <div class="card card-statistics">
      <div class="card-body">
        <div class="clearfix">
          <div class="float-left">
            <h4 class="text-warning">
              <i class="fa fa-shopping-cart highlight-icon" aria-hidden="true"></i>
            </h4>
          </div>
          <div class="float-right">
            <p class="card-text text-dark">Orders</p>
            <h4 class="bold-text">656</h4>
          </div>
        </div>
        <p class="text-muted">
          <i class="fa fa-bookmark-o mr-1" aria-hidden="true"></i> Product-wise sales
        </p>
      </div>
    </div>
  </div>
  <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 mb-4">
    <div class="card card-statistics">
      <div class="card-body">
        <div class="clearfix">
          <div class="float-left">
            <h4 class="text-success">
              <i class="fa fa-dollar highlight-icon" aria-hidden="true"></i>
            </h4>
          </div>
          <div class="float-right">
            <p class="card-text text-dark">Revenue</p>
            <h4 class="bold-text">$65656</h4>
          </div>
        </div>
        <p class="text-muted">
          <i class="fa fa-calendar mr-1" aria-hidden="true"></i> Weekly Sales
        </p>
      </div>
    </div>
  </div>
  <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 mb-4">
    <div class="card card-statistics">
      <div class="card-body">
        <div class="clearfix">
          <div class="float-left">
            <h4 class="text-primary">
              <i class="fa fa-twitter highlight-icon" aria-hidden="true"></i>
            </h4>
          </div>
          <div class="float-right">
            <p class="card-text text-dark">Followers</p>
            <h4 class="bold-text">+62,500</h4>
          </div>
        </div>
        <p class="text-muted">
          <i class="fa fa-repeat mr-1" aria-hidden="true"></i> Just Updated
        </p>
      </div>
    </div>
  </div>
</div>

app/views/admin/members/_editform.html.erb
<%= form_with(model: member,url: admin_member_path(member),method: :patch, local: true,html: {class: "forms-sample"}) do |form| %>
  <% if member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
        <% member.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :nome %>
    <%= form.text_field :first_name, class: "form-control p-input", placeholder: "Nome" %>
  </div>

  <div class="form-group">
    <%= form.label :sobrenome %>
    <%= form.text_field :last_name, class: "form-control p-input", placeholder: "Sobrenome" %>
  </div>

  <div class="form-group">
    <%= form.label :ocupação %>
    <%= form.text_field :ocupation, class: "form-control p-input", placeholder: "Ex: Desenvolvedor" %>
  </div>

  <div class="form-group">
    <%= form.label :twitter %>
    <%= form.text_field :twitter_url, class: "form-control p-input", placeholder: "twitter.com/pessoa" %>
  </div>

  <div class="form-group">
    <%= form.label :facebook %>
    <%= form.text_field :facebook_url, class: "form-control p-input", placeholder: "facebook.com/pessoa" %>
  </div>

  <div class="form-group">
    <%= form.label :instagram %>
    <%= form.text_field :instagram_url, class: "form-control p-input", placeholder: "instagram.com/pessoa" %>
  </div>

  <!--  <div class="image-upload">-->
  <!--    <label for="member_photo">-->
  <!--      <span class="fa fa-camera"></span> Foto do Membro-->
  <!--    </label>-->

  <%#= form.file_field :photo %>
  <!--  </div>-->

  <div class="form-group">
    <%= form.label :foto %><br>
    <%= form.file_field :photo, class: "btn btn-block" %>
  </div>

  <div class="actions">
    <%= form.submit "Enviar", class: "btn btn-primary btn-block" %>
  </div>
<% end %>

app/views/admin/members/_form.html.erb
<%= form_with(model: member,url: admin_members_path,method: :post, local: true,html: {class: "forms-sample"}) do |form| %>
  <% if member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
      <% member.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :nome %>
    <%= form.text_field :first_name, class: "form-control p-input", placeholder: "Nome" %>
  </div>

  <div class="form-group">
    <%= form.label :sobrenome %>
    <%= form.text_field :last_name, class: "form-control p-input", placeholder: "Sobrenome" %>
  </div>

  <div class="form-group">
    <%= form.label :ocupação %>
    <%= form.text_field :ocupation, class: "form-control p-input", placeholder: "Ex: Desenvolvedor" %>
  </div>

  <div class="form-group">
    <%= form.label :twitter %>
    <%= form.text_field :twitter_url, class: "form-control p-input", placeholder: "twitter.com/pessoa" %>
  </div>

  <div class="form-group">
    <%= form.label :facebook %>
    <%= form.text_field :facebook_url, class: "form-control p-input", placeholder: "facebook.com/pessoa" %>
  </div>

  <div class="form-group">
    <%= form.label :instagram %>
    <%= form.text_field :instagram_url, class: "form-control p-input", placeholder: "instagram.com/pessoa" %>
  </div>

<!--  <div class="image-upload">-->
<!--    <label for="member_photo">-->
<!--      <span class="fa fa-camera"></span> Foto do Membro-->
<!--    </label>-->

    <%#= form.file_field :photo %>
<!--  </div>-->

  <div class="form-group">
    <%= form.label :foto %><br>
    <%= form.file_field :photo, class: "btn btn-block" %>
  </div>

  <div class="actions">
    <%= form.submit "Enviar", class: "btn btn-primary btn-block" %>
  </div>
<% end %>

app/views/admin/members/edit.html.erb
<h1>Editing Member</h1>

<%= render 'editform', member: @member %>

app/views/admin/members/index.html.erb
<div class="card-deck">
  <div class="card col-xl-6 col-lg-6 col-md-12 col-sm-12 mb-4" style="min-height:395px;">
    <div class="card-body">
      <h5 class="card-title mb-4">Membros</h5>
      <% @members.each do |member| %>
        <div class="row d-flex align-items-center justify-items-center flex-column">
          <div class="text-center">
            <% if member.photo.attached? %>
              <%= image_tag member.photo,class: "rounded-circle avatar-img" %>
            <% end %>
          </div>
          <div class="text-center mt-3">
            <i class="fa fa-address-book-o icon-grey-big"></i>
          </div>
          <h5 class="text-center bolder"><%= member.name %></h5>
          <h6 class="text-center text-muted"><%= member.ocupation %></h6>
          <p>Facebook: <%= member.facebook_url %></p>
          <p>Twitter: <%= member.twitter_url %></p>
          <p>Instagram: <%= member.instagram_url %></p>
          <%= link_to 'Editar', edit_admin_member_path(member), class: "btn btn-warning btn-block" %>
          <%= link_to 'Deletar', admin_member_path(member), method: :delete, data: { confirm: 'Quer mesmo deletar esse membro?' },class: "btn btn-danger btn-block" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<br>

<%= link_to 'Novo Membro', new_admin_member_path, class: "btn btn-success" %>

app/views/admin/members/new.html.erb
<h1>Novo Membro</h1><br/>
<%= render 'form', member: @member %>

app/views/admin/members/show.html.erb
<p>
  <strong>First name:</strong>
  <%= @member.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @member.last_name %>
</p>

<p>
  <strong>Ocupation:</strong>
  <%= @member.ocupation %>
</p>

<p>
  <strong>Twitter url:</strong>
  <%= @member.twitter_url %>
</p>

<p>
  <strong>Facebook url:</strong>
  <%= @member.facebook_url %>
</p>

<p>
  <strong>Instagram url:</strong>
  <%= @member.instagram_url %>
</p>

app/views/layouts/admin/_footer.html.erb
<footer class="footer">
  <div class="container-fluid clearfix">
    <span class="float-right">
        <a href="#">Star Admin</a> &copy; 2017
    </span>
  </div>
</footer>

app/views/layouts/admin/_navbar.html.erb
<nav class="navbar navbar-default col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
  <div class="bg-white text-center navbar-brand-wrapper">
    <a class="navbar-brand brand-logo" href="index.html"><%= image_tag "images/logo_star_black.png" %></a>
    <a class="navbar-brand brand-logo-mini" href="index.html"><%= image_tag "images/logo_star_mini.jpg" %></a>
  </div>
  <div class="navbar-menu-wrapper d-flex align-items-center">
    <button class="navbar-toggler navbar-toggler d-none d-lg-block navbar-dark align-self-center mr-3" type="button" data-toggle="minimize">
      <span class="navbar-toggler-icon"></span>
    </button>
    <form class="form-inline mt-2 mt-md-0 d-none d-lg-block">
      <input class="form-control mr-sm-2 search" type="text" placeholder="Search">
    </form>
    <ul class="navbar-nav ml-lg-auto d-flex align-items-center flex-row">
      <li class="nav-item">
        <a class="nav-link profile-pic" href="#"><%= image_tag "images/face.jpg",class: "rounded-circle" %></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#"><i class="fa fa-th"></i></a>
      </li>
    </ul>
    <button class="navbar-toggler navbar-dark navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>
</nav>

app/views/layouts/admin/_sidebar.html.erb
<div class="container-fluid">
  <div class="row row-offcanvas row-offcanvas-right">
    <!-- partial:partials/_sidebar.html -->
    <nav class="bg-white sidebar sidebar-offcanvas" id="sidebar">
      <div class="user-info">
        <%= image_tag "images/face.jpg" %>
        <p class="name">Richard V.Welsh</p>
        <p class="designation">Manager</p>
        <span class="online"></span>
      </div>
      <ul class="nav">
        <li class="nav-item active">
          <a class="nav-link" href="<%= admin_index_path %>">
            <%= image_tag "images/icons/1.png" %>
            <span class="menu-title">Dashboard</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="pages/widgets.html">
            <%= image_tag "images/icons/2.png" %>
            <span class="menu-title">Contato</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="pages/forms/index.html">
            <%= image_tag "images/icons/005-forms.png" %>
            <span class="menu-title">Forms</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="pages/ui-elements/buttons.html">
            <%= image_tag "images/icons/4.png" %>
            <span class="menu-title">Buttons</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="pages/tables/index.html">
            <%= image_tag "images/icons/5.png" %>
            <span class="menu-title">Tables</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="pages/charts/index.html">
            <%= image_tag "images/icons/6.png" %>
            <span class="menu-title">Charts</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="pages/icons/index.html">
            <%= image_tag "images/icons/7.png" %>
            <span class="menu-title">Icons</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="pages/ui-elements/typography.html">
            <%= image_tag "images/icons/8.png" %>
            <span class="menu-title">Typography</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" data-toggle="collapse" href="#sample-pages" aria-expanded="false" aria-controls="sample-pages">
            <%= image_tag "images/icons/9.png" %>
            <span class="menu-title">Sample Pages<i class="fa fa-sort-down"></i></span>
          </a>
          <div class="collapse" id="sample-pages">
            <ul class="nav flex-column sub-menu">
              <li class="nav-item">
                <a class="nav-link" href="pages/samples/blank_page.html">
                  Blank Page
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="pages/samples/login.html">
                  Login
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="pages/samples/register.html">
                  Register
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="pages/samples/404.html">
                  404
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="pages/samples/500.html">
                  500
                </a>
              </li>
            </ul>
          </div>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">
            <%= image_tag "images/icons/10.png" %>
            <span class="menu-title">Settings</span>
          </a>
        </li>
      </ul>
    </nav>

<!-- partial -->
  </div>
</div>